#!/bin/bash -f
# Vivado (TM) v2016.3 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Mar 30 15:39:12 CEST 2017
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-load "/opt/Xilinx/Vivado/2016.3/lib/lnx64.o/libxil_vcs.so:xilinx_register_systf" -full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm microblaze_v10_0_0 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_10 blk_mem_gen_v8_3_4 axi_lite_ipif_v3_0_4 axi_intc_v4_1_8 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_uartlite_v2_0_14 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_10 fifo_generator_v13_1_2 axi_data_fifo_v2_1_9 axi_crossbar_v2_1_11 interrupt_control_v3_1_4 axi_iic_v2_0_13 processing_system7_bfm_v2_0_5 proc_sys_reset_v5_0_10 mdm_v3_2_7 axi_gpio_v2_0_12 axi_timer_v2_0_12 axi_protocol_converter_v2_1_10 axi_clock_converter_v2_1_9 axi_dwidth_converter_v2_1_10)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2016.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "/opt/Xilinx/Vivado/2016.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2016.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2016.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_0 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7262/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_0/sim/design_1_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/162e/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_dlmb_v10_1/sim/design_1_dlmb_v10_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ilmb_v10_1/sim/design_1_ilmb_v10_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_10 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/f4d9/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/sim/design_1_dlmb_bram_if_cntlr_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/sim/design_1_ilmb_bram_if_cntlr_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/59b0/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_lmb_bram_1/sim/design_1_lmb_bram_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_8 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/3dfb/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_axi_intc_1/sim/design_1_microblaze_0_axi_intc_1.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/2e37/xlconcat.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_xlconcat_1/sim/design_1_microblaze_0_xlconcat_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_14 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/8df9/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_uartlite_0_0/sim/design_1_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7efe/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/a807/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_2 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/a807/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/a807/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/10b8/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/d552/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/e956/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_13 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/3889/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_iic_0_0/sim/design_1_axi_iic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work processing_system7_bfm_v2_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl/processing_system7_bfm_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/hdl/design_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_clk_wiz_0_100M_2/sim/design_1_rst_clk_wiz_0_100M_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_7 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/911b/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_mdm_0_0/sim/design_1_mdm_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_12 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/475c/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_6/sim/design_1_axi_gpio_0_6.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_7/sim/design_1_axi_gpio_0_7.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_8/sim/design_1_axi_gpio_0_8.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_9/sim/design_1_axi_gpio_0_9.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_12 $vhdlan_opts \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/eace/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_timer_0_0/sim/design_1_axi_timer_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_iic_0_2/sim/design_1_axi_iic_0_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_axi_intc_2/sim/design_1_microblaze_0_axi_intc_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_2/sim/design_1_microblaze_0_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_xlconcat_2/sim/design_1_microblaze_0_xlconcat_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_uartlite_0_2/sim/design_1_axi_uartlite_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_2/sim/design_1_xbar_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_dlmb_v10_2/sim/design_1_dlmb_v10_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ilmb_v10_2/sim/design_1_ilmb_v10_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_dlmb_bram_if_cntlr_2/sim/design_1_dlmb_bram_if_cntlr_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/sim/design_1_ilmb_bram_if_cntlr_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_lmb_bram_2/sim/design_1_lmb_bram_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0_1/sim/design_1_rst_clk_wiz_0_100M_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mdm_0_3/sim/design_1_mdm_0_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_11/sim/design_1_axi_gpio_0_11.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_2/sim/design_1_axi_gpio_1_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_2_1/sim/design_1_axi_gpio_2_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_3_1/sim/design_1_axi_gpio_3_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_4_1/sim/design_1_axi_gpio_4_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_timer_0_1/sim/design_1_axi_timer_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_iic_0_5/sim/design_1_axi_iic_0_5.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_axi_intc_3/sim/design_1_microblaze_0_axi_intc_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_4/sim/design_1_microblaze_0_4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_microblaze_0_xlconcat_3/sim/design_1_microblaze_0_xlconcat_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_uartlite_0_5/sim/design_1_axi_uartlite_0_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_3/sim/design_1_xbar_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_dlmb_v10_3/sim/design_1_dlmb_v10_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ilmb_v10_3/sim/design_1_ilmb_v10_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_dlmb_bram_if_cntlr_3/sim/design_1_dlmb_bram_if_cntlr_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/sim/design_1_ilmb_bram_if_cntlr_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_lmb_bram_3/sim/design_1_lmb_bram_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0_2/sim/design_1_rst_clk_wiz_0_100M_0_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mdm_0_4/sim/design_1_mdm_0_4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_12/sim/design_1_axi_gpio_0_12.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_3/sim/design_1_axi_gpio_1_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_2_2/sim/design_1_axi_gpio_2_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_3_2/sim/design_1_axi_gpio_3_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_4_2/sim/design_1_axi_gpio_4_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_timer_0_2/sim/design_1_axi_timer_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/4a8b/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/cf3b/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/4a86/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/db52" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../multiple_microblaze.srcs/sources_1/bd/design_1/ipshared/2527/hdl" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_2/sim/design_1_auto_ds_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_3/sim/design_1_auto_ds_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_4/sim/design_1_auto_ds_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_5/sim/design_1_auto_ds_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_6/sim/design_1_auto_ds_6.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_7/sim/design_1_auto_ds_7.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_8/sim/design_1_auto_ds_8.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_9/sim/design_1_auto_ds_9.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_10/sim/design_1_auto_ds_10.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_11/sim/design_1_auto_ds_11.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_12/sim/design_1_auto_ds_12.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_13/sim/design_1_auto_ds_13.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_14/sim/design_1_auto_ds_14.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_15/sim/design_1_auto_ds_15.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_16/sim/design_1_auto_ds_16.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_17/sim/design_1_auto_ds_17.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_1/sim/design_1_auto_us_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_18/sim/design_1_auto_ds_18.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_19/sim/design_1_auto_ds_19.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_20/sim/design_1_auto_ds_20.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_21/sim/design_1_auto_ds_21.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_22/sim/design_1_auto_ds_22.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_23/sim/design_1_auto_ds_23.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_24/sim/design_1_auto_ds_24.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_25/sim/design_1_auto_ds_25.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_26/sim/design_1_auto_ds_26.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_2/sim/design_1_auto_us_2.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/ravi/ThesisWork/multiple_microblaze/multiple_microblaze.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
