# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrain.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_1 || ORIG_REF_NAME==design_1_dlmb_v10_1}]

# IP: bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_1 || ORIG_REF_NAME==design_1_ilmb_v10_1}]

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/design_1_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_1}]

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_1}]

# IP: bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_1 || ORIG_REF_NAME==design_1_lmb_bram_1}]

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_1/design_1_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_1}]

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_1 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_1}]

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_1/design_1_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_1 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_1}]

# IP: bd/design_1/ip/design_1_mdm_1_1/design_1_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_1 || ORIG_REF_NAME==design_1_mdm_1_1}]

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_0}]

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}]

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1}]

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_3 || ORIG_REF_NAME==design_1_microblaze_0_3}]

# IP: bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_0 || ORIG_REF_NAME==design_1_microblaze_1_0}]

# IP: bd/design_1/ip/design_1_dlmb_v10_5/design_1_dlmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_5 || ORIG_REF_NAME==design_1_dlmb_v10_5}]

# IP: bd/design_1/ip/design_1_ilmb_v10_5/design_1_ilmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_5 || ORIG_REF_NAME==design_1_ilmb_v10_5}]

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_5/design_1_dlmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_5 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_5}]

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_5/design_1_ilmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_5 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_5}]

# IP: bd/design_1/ip/design_1_lmb_bram_5/design_1_lmb_bram_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_5 || ORIG_REF_NAME==design_1_lmb_bram_5}]

# IP: bd/design_1/ip/design_1_microblaze_1_axi_periph_1/design_1_microblaze_1_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_axi_periph_1 || ORIG_REF_NAME==design_1_microblaze_1_axi_periph_1}]

# IP: bd/design_1/ip/design_1_microblaze_1_axi_intc_1/design_1_microblaze_1_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_axi_intc_1 || ORIG_REF_NAME==design_1_microblaze_1_axi_intc_1}]

# IP: bd/design_1/ip/design_1_microblaze_1_xlconcat_1/design_1_microblaze_1_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_xlconcat_1 || ORIG_REF_NAME==design_1_microblaze_1_xlconcat_1}]

# IP: bd/design_1/ip/design_1_axi_iic_0_3/design_1_axi_iic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_3 || ORIG_REF_NAME==design_1_axi_iic_0_3}]

# IP: bd/design_1/ip/design_1_axi_uartlite_0_3/design_1_axi_uartlite_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_3 || ORIG_REF_NAME==design_1_axi_uartlite_0_3}]

# IP: bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_5 || ORIG_REF_NAME==design_1_xbar_5}]

# IP: bd/design_1/ip/design_1_dlmb_v10_6/design_1_dlmb_v10_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_6 || ORIG_REF_NAME==design_1_dlmb_v10_6}]

# IP: bd/design_1/ip/design_1_ilmb_v10_6/design_1_ilmb_v10_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_6 || ORIG_REF_NAME==design_1_ilmb_v10_6}]

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_6/design_1_dlmb_bram_if_cntlr_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_6 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_6}]

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_6/design_1_ilmb_bram_if_cntlr_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_6 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_6}]

# IP: bd/design_1/ip/design_1_lmb_bram_6/design_1_lmb_bram_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_6 || ORIG_REF_NAME==design_1_lmb_bram_6}]

# IP: bd/design_1/ip/design_1_microblaze_2_axi_periph_0/design_1_microblaze_2_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_2_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_2_axi_periph_0}]

# IP: bd/design_1/ip/design_1_microblaze_2_axi_intc_0/design_1_microblaze_2_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_2_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_2_axi_intc_0}]

# IP: bd/design_1/ip/design_1_microblaze_2_xlconcat_0/design_1_microblaze_2_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_2_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_2_xlconcat_0}]

# IP: bd/design_1/ip/design_1_axi_iic_0_4/design_1_axi_iic_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_4 || ORIG_REF_NAME==design_1_axi_iic_0_4}]

# IP: bd/design_1/ip/design_1_xbar_6/design_1_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_6 || ORIG_REF_NAME==design_1_xbar_6}]

# IP: bd/design_1/ip/design_1_axi_uartlite_0_4/design_1_axi_uartlite_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_4 || ORIG_REF_NAME==design_1_axi_uartlite_0_4}]

# XDC: bd/design_1/design_1_ooc.xdc
