# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ravi/ThesisWork/multiple_microblaze/multiple_microblaze.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_17/design_1_auto_ds_17.xci
# IP: The module: 'design_1_auto_ds_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ravi/ThesisWork/multiple_microblaze/multiple_microblaze.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_17/design_1_auto_ds_17_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_17'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/ravi/ThesisWork/multiple_microblaze/multiple_microblaze.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_17/design_1_auto_ds_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/ravi/ThesisWork/multiple_microblaze/multiple_microblaze.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_17/design_1_auto_ds_17.xci
# IP: The module: 'design_1_auto_ds_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ravi/ThesisWork/multiple_microblaze/multiple_microblaze.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_17/design_1_auto_ds_17_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/ravi/ThesisWork/multiple_microblaze/multiple_microblaze.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_17/design_1_auto_ds_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
